Setup unified fmt script
Set the minimum Bash version to 5.2 and normalize text files to LF.

diff --git a/script/bundle-macos b/script/bundle-macos
--- a/script/bundle-macos
+++ b/script/bundle-macos
@@ -2,6 +2,11 @@
 
 set -euo pipefail
 
+if ((BASH_VERSINFO[0] < 5 || BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] < 2)); then
+  echo "Bash 5.2 or later is required" >&2
+  exit 1
+fi
+
 CARGO_BUNDLE_VERSION="0.11.0"
 
 if [[ ${1:-} == "-h" || ${1:-} == "--help" ]]; then
diff --git a/script/linux b/script/linux
--- a/script/linux
+++ b/script/linux
@@ -2,6 +2,11 @@
 
 set -euo pipefail
 
+if ((BASH_VERSINFO[0] < 5 || BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] < 2)); then
+  echo "Bash 5.2 or later is required" >&2
+  exit 1
+fi
+
 if [[ $# -gt 0 ]]; then
   echo "Unexpected argument: $1" >&2
   exit 1
