Show help message instead

diff --git a/script/bundle-linux b/script/bundle-linux
--- a/script/bundle-linux
+++ b/script/bundle-linux
@@ -2,7 +2,12 @@
 
 set -euo pipefail
 
-if [[ $# -eq 1 && ($1 == "-h" || $1 == "--help") ]]; then
+if [[ ${1:-} == "-h" || ${1:-} == "--help" ]]; then
+  if [[ $# -ne 1 ]]; then
+    echo "Unexpected argument: $2" >&2
+    echo "Run ./script/bundle-linux --help" >&2
+    exit 1
+  fi
   echo "Usage: ./script/bundle-linux [OPTIONS]"
   echo "Build a Linux application bundle."
   echo "Options:"
@@ -12,7 +17,7 @@ if [[ $# -eq 1 && ($1 == "-h" || $1 == "--help") ]]; then
 fi
 if [[ $# -gt 2 ]]; then
   echo "Unexpected argument: $3" >&2
-  echo "Usage: ./script/bundle-linux [OPTIONS]" >&2
+  echo "Run ./script/bundle-linux --help" >&2
   exit 1
 fi
 
@@ -22,14 +27,15 @@ case "${1:-}" in
   ;;
 --arch)
   if [[ $# -ne 2 || -z ${2:-} ]]; then
-    echo "Usage: ./script/bundle-linux [OPTIONS]" >&2
+    echo "Missing value for --arch" >&2
+    echo "Run ./script/bundle-linux --help" >&2
     exit 1
   fi
   arch="$2"
   ;;
 *)
   echo "Unexpected argument: $1" >&2
-  echo "Usage: ./script/bundle-linux [OPTIONS]" >&2
+  echo "Run ./script/bundle-linux --help" >&2
   exit 1
   ;;
 esac
diff --git a/script/bundle-macos b/script/bundle-macos
--- a/script/bundle-macos
+++ b/script/bundle-macos
@@ -4,7 +4,12 @@ set -euo pipefail
 
 CARGO_BUNDLE_VERSION="0.11.0"
 
-if [[ $# -eq 1 && ($1 == "-h" || $1 == "--help") ]]; then
+if [[ ${1:-} == "-h" || ${1:-} == "--help" ]]; then
+  if [[ $# -ne 1 ]]; then
+    echo "Unexpected argument: $2" >&2
+    echo "Run ./script/bundle-macos --help" >&2
+    exit 1
+  fi
   echo "Usage: ./script/bundle-macos [OPTIONS]"
   echo "Build a macOS application bundle and disk image."
   echo "Options:"
@@ -14,7 +19,7 @@ if [[ $# -eq 1 && ($1 == "-h" || $1 == "--help") ]]; then
 fi
 if [[ $# -gt 2 ]]; then
   echo "Unexpected argument: $3" >&2
-  echo "Usage: ./script/bundle-macos [OPTIONS]" >&2
+  echo "Run ./script/bundle-macos --help" >&2
   exit 1
 fi
 
@@ -24,14 +29,15 @@ case "${1:-}" in
   ;;
 --arch)
   if [[ $# -ne 2 || -z ${2:-} ]]; then
-    echo "Usage: ./script/bundle-macos [OPTIONS]" >&2
+    echo "Missing value for --arch" >&2
+    echo "Run ./script/bundle-macos --help" >&2
     exit 1
   fi
   arch="$2"
   ;;
 *)
   echo "Unexpected argument: $1" >&2
-  echo "Usage: ./script/bundle-macos [OPTIONS]" >&2
+  echo "Run ./script/bundle-macos --help" >&2
   exit 1
   ;;
 esac
