Canonical bundle versions

diff --git a/script/get-version b/script/get-version
--- a/script/get-version
+++ b/script/get-version
@@ -9,8 +9,13 @@ fi
 
 version=$("${CARGO:-cargo}" metadata --no-deps --format-version=1 | jq --exit-status --raw-output '.packages[] | select(.name == "zaku") | .version')
 
-if [[ "$version" =~ ^([0-9]+)\.([0-9]+)\.0$ ]]; then
-  echo "${BASH_REMATCH[1]}.${BASH_REMATCH[2]}"
+if [[ "$version" == *+* ]]; then
+  echo "Version cannot contain build metadata" >&2
+  exit 1
+fi
+
+if [[ "$version" =~ ^([0-9]+)\.([0-9]+)\.0(-.+)?$ ]]; then
+  echo "${BASH_REMATCH[1]}.${BASH_REMATCH[2]}${BASH_REMATCH[3]}"
 else
   echo "$version"
 fi
